### PR TITLE
Add quantity option

### PR DESCRIPTION
**Pull request by macbookandrew**
Add option to hide/show quantity field on frontend, as well as add some other minor UI improvements in the backend.

### CODE REVIEW

**Comment by kfaruque** [comment]
Quantity & Price should be side by side i.e ordering of the column should be price then quantity.

**Comment by macbookandrew** [comment]
@kfaruque Sorry…not sure if I’m missing something or what, but that’s what I’m seeing…

Curent column order:

1. Image
2. SKU
3. Description
4. Dimensions
5. Weight
6. Stock
7. Price
8. Quantity

**Comment by kfaruque** [comment]
I am not sure in my case varition attributes come within quantity and
price. I am giving you the screen shot.





[image: Inline image 1]

Regards,

Faruque

**Comment by macbookandrew** [comment]
@kfaruque The screenshot didn’t make it through…

**Comment by kfaruque** [comment]
Actuallay if i create custom product variation then in varition table it
shows between price and quantity i.e column sequence became price, type,
size, partid, stock, quantity but it should be type, partid, stock, price,
quantity. that i want to mean.

**Comment by macbookandrew** [comment]
@kfaruque Any chance you can attach a screenshot?

**Comment by kfaruque** [comment]
Here is the screenshot

[image: Inline image 1]

**Comment by macbookandrew** [comment]
Screenshot still isn’t coming through. Can you open the thread in your browser and upload it there instead of emailing it?

Thanks

**Comment by kfaruque** [comment]
Here is the screenshot

image

**Comment by macbookandrew** [comment]
@kfaruque Sorry, just had time to look at this. Sounds like a separate issue. You might want to open a separate issue for it.

**Pull request merged**
